//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : costentry.cpp
//  @ Date : 11.10.17
//  @ Author :
//
//


#include "../../headers/datastructures/costentry.h"
#include "../../headers/errors/product.h"
#include "../../headers/errors/date.h"

namespace DataStructures
{
    CostEntry::CostEntry(Product *product, int count, Date date)
    {

    }

    Product CostEntry::getProduct()
    {

    }

    int CostEntry::getCount()
    {

    }

    Date CostEntry::getDate()
    {

    }

}
