//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : date.cpp
//  @ Date : 11.10.17
//  @ Author : 
//
//


#include "date.h"

namespace DataStructures
{
    void Date::Date(int d, int m, int y)
    {
    
    }
    
    int Date::getDay()
    {
    
    }
    
    int Date::getMonth()
    {
    
    }
    
    int Date::getYear()
    {
    
    }
    
}
