//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : product.cpp
//  @ Date : 11.10.17
//  @ Author :
//
//


#include "product.h"

namespace DataStructures
{
    Product::Product(string name, int price)
    {

    }

    string Product::getName()
    {

    }

    int Product::getPrice()
    {

    }

    void Product::setName(string name)
    {

    }

    void Product::setPrice(int price)
    {

    }

}
