//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : menu.cpp
//  @ Date : 11.10.17
//  @ Author :
//
//


#include "../../headers/cmdinterface/menu.h"

namespace CMDInterface
{
    void Menu::show()
    {

    }

    void Menu::input(int operation)
    {

    }

}
