//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : costentry.h
//  @ Date : 11.10.17
//  @ Author :
//
//


#if !defined(_COSTENTRY_H)
#define _COSTENTRY_H

#include "product.h"
#include "date.h"

namespace DataStructures
{
    class CostEntry
    {
    private:
        int id;
        Product product;
        int count;
        Date date;
    public:
        CostEntry(Product *product, int count, Date date);
        Product getProduct();
        int getCount();
        Date getDate();
    };
}

#endif  //_COSTENTRY_H
