//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : product.h
//  @ Date : 11.10.17
//  @ Author :
//
//


#if !defined(_PRODUCT_H)
#define _PRODUCT_H

#include <string>
using namespace std;


namespace DataStructures
{
    class Product
    {
    private:
        string name;
        int price;
    public:
        Product(string name, int price);
        string getName();
        int getPrice();
        void setName(string name);
        void setPrice(int price);
    };
}

#endif  //_PRODUCT_H
