//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : database.h
//  @ Date : 11.10.17
//  @ Author :
//
//


#if !defined(_DATABASE_H)
#define _DATABASE_H

#include "../datastructures/costentry.h"
#include "../datastructures/date.h"
#include "../errors/product.h"

using namespace DataStructures;

namespace Controller
{
    class DataBase
    {
    private:
        CostEntry costs;
    public:
        void add(CostEntry costEntry);
        void get(int id);
        void get(string product_name);
        void get(Date date);
        void change(Product product_old, Product product_new);
        void remove(int id);
        void import(string filename);
        void _export(string filename);
    };
}

#endif  //_DATABASE_H
