//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : date.h
//  @ Date : 11.10.17
//  @ Author : 
//
//


#if !defined(_DATE_H)
#define _DATE_H


namespace ERRORS
{
    enum DATE
    {
        INCORRECT_DATE
    };
}

#endif  //_DATE_H
