//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : operations.h
//  @ Date : 11.10.17
//  @ Author : 
//
//


#if !defined(_OPERATIONS_H)
#define _OPERATIONS_H


namespace ERRORS
{
    enum Operations
    {
        ADD,
        GET,
        CHANGE,
        REMOVE,
        IMPORT,
        EXPORT
    };
}

#endif  //_OPERATIONS_H
