//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : product.h
//  @ Date : 11.10.17
//  @ Author : 
//
//


#if !defined(_PRODUCT_H)
#define _PRODUCT_H


namespace ERRORS
{
    enum PRODUCT
    {
        EMPTY_NAME,
        INCORRECT_PRICE
    };
}

#endif  //_PRODUCT_H
