//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : database.cpp
//  @ Date : 11.10.17
//  @ Author :
//
//


#include "../../headers/controller/database.h"
#include "../../headers/datastructures/costentry.h"
#include "../../headers/errors/date.h"
#include "../../headers/errors/product.h"

namespace Controller
{
    void DataBase::add(CostEntry costEntry)
    {

    }

    void DataBase::get(int id)
    {

    }

    void DataBase::get(string product_name)
    {

    }

    void DataBase::get(Date date)
    {

    }

    void DataBase::change(Product product_old, Product product_new)
    {

    }

    void DataBase::remove(int id)
    {

    }

    void DataBase::import(string filename)
    {

    }

    void DataBase::_export(string filename)
    {

    }

}
