//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : menu.h
//  @ Date : 11.10.17
//  @ Author : 
//
//


#if !defined(_MENU_H)
#define _MENU_H


namespace CMDInterface
{
    class Menu
    {
    private:
        int db;
    public:
        void show();
        void input(int operation);
    };
}

#endif  //_MENU_H
